### PR TITLE
Fix debugger

### PR DESCRIPTION
**Pull request by kuzmas**

### CODE REVIEW

**Comment by koush** [comment]
Does the debugger even work in emscripten mode?

**Comment by kuzmas** [comment]
Short answer: Yes, it does.

More words: I had to make some more changes as our project on Windows requires to be compiled with MSVC and QuickJS (the original and therefore this debug-enabled as well) is not MSVC-compatible, but those changes should not affect it.

**Comment by sponge** [comment]
Sorry to impede on a closed PR, but would your fork with MSVC + debugging happen to be publicly available anywhere? I'm currently using a fork that supports MSVC but would love to have the debugger support without pouring through the changes and writing the Windows socket myself.

**Comment by kuzmas** [comment]
@sponge 
We use `boost::asio::ip::tcp::socket` in our project to avoid dealing with raw windows sockets, but that code is proprietary and I'm not at liberty to make it public, sorry.

**Pull request merged**
